# Generated by Django 6.0.3 on 2026-04-05 03:42

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Guild",
            fields=[
                ("id", models.BigIntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                (
                    "lang",
                    models.CharField(
                        choices=[("en", "English"), ("es", "Spanish")], default="en", max_length=2
                    ),
                ),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
