# Generated by Django 6.0.3 on 2026-04-11 19:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="guild",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="guild",
            name="version",
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="guild",
            name="lang",
            field=models.CharField(
                choices=[("en", "(EN) English"), ("es", "(ES) Spanish")], default="en", max_length=2
            ),
        ),
    ]
