# Generated by Django 6.0.3 on 2026-04-14 18:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_guild_updated_at_guild_version_alter_guild_lang"),
    ]

    operations = [
        migrations.CreateModel(
            name="Language",
            fields=[
                ("code", models.CharField(max_length=2, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name="guild",
            name="name",
        ),
        migrations.AlterField(
            model_name="guild",
            name="lang",
            field=models.ForeignKey(
                default="en", on_delete=django.db.models.deletion.CASCADE, to="api.language"
            ),
        ),
    ]
