name: Deploy by Tag (Reusable)

on:
  workflow_call:
    inputs:
      image_tag:
        description: Docker image tag to deploy
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy selected image tag to VPS
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ vars.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            set -e

            echo "${{ secrets.DOCKER_TOKEN }}" | \
              docker login -u "${{ vars.DOCKER_USER }}" --password-stdin

            docker stop ${{ vars.DOCKER_CONTAINER }} || true
            docker rm ${{ vars.DOCKER_CONTAINER }} || true

            docker pull ${{ vars.DOCKER_USER }}/${{ vars.DOCKER_IMAGE }}:${{ inputs.image_tag }}

            NETWORK_ARGS=""
            if [ -n "${{ vars.DOCKER_NETWORK }}" ]; then
              NETWORK_ARGS="--network ${{ vars.DOCKER_NETWORK }}"
            fi

            docker run -d --name '${{ vars.DOCKER_CONTAINER }}' \
              -e 'PRODUCTION=True' \
              -e 'DJANGO_SECRET_KEY=${{ secrets.DJANGO_SECRET_KEY }}' \
              -e 'HOSTS=${{ vars.HOSTS }}' \
              -e 'CORS_ALLOWED=${{ vars.CORS_ALLOWED }}' \
              -e 'CSRF_TRUSTED=${{ vars.CSRF_TRUSTED }}' \
              -e 'PG_DB=${{ vars.PG_DB }}' \
              -e 'PG_USER=${{ secrets.PG_USER }}' \
              -e 'PG_PASS=${{ secrets.PG_PASS }}' \
              -e 'PG_HOST=${{ vars.PG_HOST }}' \
              -e 'PG_PORT=${{ vars.PG_PORT }}' \
              -p '${{ vars.DOCKER_HOST_PORT }}:8000' \
              --restart unless-stopped \
              $NETWORK_ARGS \
              '${{ vars.DOCKER_USER }}/${{ vars.DOCKER_IMAGE }}:${{ inputs.image_tag }}'
