name: Deploy in VPS

on:
  workflow_dispatch:

  workflow_run:
    workflows: ["Push Docker Image"]
    types:
      - completed

jobs:
  deploy_latest:
    if: ${{ github.event_name == 'workflow_dispatch' || (github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success') }}
    runs-on: ubuntu-latest

    steps:
      - name: Deploy latest image to VPS
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ vars.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            set -e

            echo "${{ secrets.DOCKER_TOKEN }}" | \
              docker login -u "${{ vars.DOCKER_USER }}" --password-stdin

            docker stop ${{ vars.DOCKER_IMAGE }}-app || true
            docker rm ${{ vars.DOCKER_IMAGE }}-app || true
            docker pull ${{ vars.DOCKER_USER }}/${{ vars.DOCKER_IMAGE }}:latest

            NETWORK_ARGS=""
            if [ -n "${{ vars.DOCKER_NETWORK }}" ]; then
              NETWORK_ARGS="--network ${{ vars.DOCKER_NETWORK }}"
            fi

            docker run -d --name '${{ vars.DOCKER_IMAGE }}-app' \
              -e 'PRODUCTION=True' \
              -e 'USE_SSL=True' \
              -e 'DJANGO_SECRET_KEY=${{ secrets.DJANGO_SECRET_KEY }}' \
              -e 'HOSTS=${{ vars.HOSTS }}' \
              -e 'CORS_ALLOWED=${{ vars.FRONTEND_ALLOWED }}' \
              -e 'CSRF_TRUSTED=${{ vars.FRONTEND_ALLOWED }}' \
              -e 'PG_DB=${{ vars.PG_DB }}' \
              -e 'PG_USER=${{ secrets.PG_USER }}' \
              -e 'PG_PASS=${{ secrets.PG_PASS }}' \
              -e 'PG_HOST=${{ vars.PG_HOST }}' \
              -e 'PG_PORT=5432' \
              -e 'SESSION_DOMAIN=${{ vars.SESSION_DOMAIN }}' \
              -e 'REDIS_URL=${{ vars.REDIS_URL }}' \
              -e 'DISCORD_CLIENT_ID=${{ vars.DISCORD_CLIENT_ID }}' \
              -e 'DISCORD_CLIENT_SECRET=${{ secrets.DISCORD_CLIENT_SECRET }}' \
              -e 'DISCORD_REDIRECT_URI=${{ vars.DISCORD_REDIRECT_URI }}' \
              -e 'FRONTEND_URL=${{ vars.FRONTEND_URL }}' \
              -e 'FRONTEND_AUTH_CALLBACK_URL=${{ vars.FRONTEND_AUTH_CALLBACK_URL }}' \
              -p '${{ vars.DOCKER_HOST_PORT }}:8000' \
              --restart unless-stopped \
              $NETWORK_ARGS \
              '${{ vars.DOCKER_USER }}/${{ vars.DOCKER_IMAGE }}:latest'
